8 feature 0 basic entities
CSC207-2023Y-UofT/course-project-DoorKeepers pull request #9
Opened 2023-07-18 02:25 UTC by katarinaavucic

Added base entities and tests as described in CRC cards. Also added an exception for any error with the entities (that may be used later). Please read all methods and documentation so that we can ensure they are good before building the rest of our project!

2023-07-19 23:42 UTC, aricasas requested changes
This seems great! I just added some comments about things I think could be renamed, but other than that it all looks good to me. Thanks Kat!

2023-07-19 23:42 UTC, aricasas commented on src/main/java/entities/MonthlyStorage.java
> +    public void setCategoryData(Category category){
Could this be named addCategory instead? I think that would be more accurate to what the method does

2023-07-19 23:42 UTC, aricasas commented on src/main/java/entities/MonthlyStorage.java
> +    public void setExpenseData(Expense expense){
Also in here maybe change name to addExpense

2023-07-19 23:42 UTC, aricasas commented on src/main/java/entities/SessionStorage.java
> +    public void setMonthlyData(MonthlyStorage month){
can we change the name of this one to addMonthlyData? Cause this one is adding something to the array instead of setting it

2023-07-19 23:42 UTC, aricasas commented on src/main/java/entities/SessionStorage.java
> +    public void setRecurData(Expense recurExpense){
change to addRecurExpense?

2023-07-19 23:42 UTC, aricasas commented on src/main/java/entities/SessionStorage.java
> +    public MonthlyStorage getMonthlyData(int currentMonth) throws EntityException {
Could we change the parameter name to just month? Because this method should work with any month right, not just the current one

2023-07-20 01:37 UTC, luluwuwu approved these changes, later dismissed
Everything looks great to me!!

2023-07-20 03:32 UTC, YinLingithub commented on src/main/java/entities/Category.java
1. Don't need colon after "@param _parameter_". 
2. Javadoc are needed above the classes too. 
These points applies to all files.

2023-07-20 03:38 UTC, YinLingithub requested changes
1. Don't need colon after "@param _parameter_". 
2. Javadoc are needed above the classes too. 
These points applies to all files.

2023-07-20 03:46 UTC, YinLingithub commented on src/main/java/entities/MonthlyStorage.java
Also, we need setters to edit expenses and categories.

2023-07-20 23:38 UTC, aricasas approved these changes

2023-07-20 23:52 UTC, luluwuwu approved these changes
Remember to complete javadoc!

2023-07-20 23:53 UTC, YinLingithub approved these changes

2023-07-20 23:54 UTC, merged